FROM maven:3.9-eclipse-temurin-21-alpine AS builder

ARG SERVICE_DIR
WORKDIR /build

COPY backend/shared ./shared
RUN --mount=type=cache,target=/root/.m2 cd shared && mvn -U -DskipTests install


COPY backend/${SERVICE_DIR} ./service
RUN --mount=type=cache,target=/root/.m2 cd service && mvn -U -DskipTests package


FROM eclipse-temurin:21-jre-alpine

ARG SERVICE_PORT=8080
WORKDIR /app

COPY --from=builder /build/service/target/*.jar app.jar

EXPOSE ${SERVICE_PORT}

ENTRYPOINT ["java", "-jar", "app.jar"]