spring.application.name=integration-service
server.port=8091

spring.kafka.bootstrap-servers=localhost:9092

# Webhook URL here (https://api.slack.com/messaging/webhooks)
integration.slack.webhook-url=

management.endpoints.web.exposure.include=health,info,prometheus
management.prometheus.metrics.export.enabled=true

services.project-service.url=http://localhost:8082
services.ingestion-service.url=http://localhost:8083

integration.github.webhook-secret=

integration.jira.base-url=
integration.jira.email=
integration.jira.api-token=
integration.jira.project-key=