spring.application.name=integration-service
server.port=8091

spring.kafka.bootstrap-servers=localhost:9092

# Webhook URL here (https://api.slack.com/messaging/webhooks)
integration.slack.webhook-url=

management.endpoints.web.exposure.include=health,info,prometheus
management.prometheus.metrics.export.enabled=true