spring:
  application:
    name: ai-gateway
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8090

grpc:
  client:
    parser-service:
      address: static://localhost:50051
      negotiation-type: plaintext

services:
  graph-service:
    url: http://localhost:8085
  search-service:
    url: http://localhost:8086

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  prometheus:
    metrics:
      export:
        enabled: true
